PART 18
Evgeniy-ES/TetsGuru pull request #18
Opened 2021-12-20 11:33 UTC by Evgeniy-ES

2021-12-20 18:38 UTC, BubuntuClu requested changes

2021-12-20 18:38 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    @badge = Badge.all
`badges = `

2021-12-20 18:38 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    @rule = Rule.all
`rules = ...`

у тебя ведь тут много объектов

2021-12-20 18:38 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @rule = Rule.all
а тут зачем правила выводить? зачем вообще этот контроллер?

2021-12-20 18:38 UTC, BubuntuClu commented on app/controllers/my_badges_controller.rb
> +    @rule = Rule.all
тут зачем правила?

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/badge.rb
> +    Test.where(category_id: BACKEND_ID).each {|x| tests_backend.push(x.id)}
используй `pluck` вместо своего велосепеда

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/badge.rb
> +  def complete_all_tests_backend(user_id)
все методы должны быть в сервисе, выдающем награду.
это не задача модели считать эту информацию

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      check_badge
так "нельзя" делать. сейчас это ниндзя метод, который запускает под собой какую-то логику. ожидаемое поведение что ты узнаешь просто результат прохождения теста - успех/неуспех. а под капотом там целая рокета в космос запускается

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    add_badge("Passed all backend tests") if badge.complete_all_tests_backend(user.id)
если баджей будет 15, то тут будет 15 ифов? надо придумать что-то с этим

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    badges = Badge.where(rule_id: rule.id)
ты находишь все баджи правила и присваиваешь пользователю их все? в чем смысл?

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      check_badge
нужно сделать сервис, который будет управлять выдачей баджей

2021-12-20 18:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      self.current_question_id = Question.last.id
это что-то странное тут происходит. какая тут логика закладывается?

2021-12-20 18:38 UTC, BubuntuClu commented on db/migrate/20211213121441_create_user_badges.rb
> +
задавай еще значение для правила, какое использовать для расчетов. допустим у тебя правило "прохождение всех тестов категории", а название категории как раз храни в параметре. чтобы на одно правило, можно было создать несколько баджей с разными критериями

2021-12-20 19:16 UTC, Evgeniy-ES commented on db/migrate/20211213121441_create_user_badges.rb
> +
Но у меня правила задаются в отдельной таблице rule и я как раз могу на одно и тоже правило создать несколько баджей с разными описаниями и ссылкой.

2021-12-20 19:18 UTC, Evgeniy-ES commented on app/models/test_passage.rb
> +    badges = Badge.where(rule_id: rule.id)
Если есть несколько баджей с одинаковыми правилами, но с разными именами и ссылками, то при срабатывания правила они присваиваются пользователю

2021-12-22 18:57 UTC, BubuntuClu requested changes

2021-12-22 18:57 UTC, BubuntuClu commented on app/controllers/my_badges_controller.rb
> +    @rules = Rule.all
зачем пользователю правила видеть?

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +   tests_user = TestPassage.where(user_id: testpassage.user_id, test_id: testpassage.test_id).pluck(:test_id)
нужно добавить проверку что тест был пройден успешно

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +  def passed_all_parametr_tests(badge, testpassage)
весь код выдачи баджей/проверки баджей должен делать сервис, а не модель

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +    backend_id = {'backend' => 2, 'frontend' => '3'}
зачем нужен этот список? это костыль для обработки. так же при добавлении баджа с новой категорией, нужно будет править код, что рушит концепцию

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +      tests_backend = Test.where(category_id: backend_id[badge.parametr]).pluck(:id)
у тебя есть метод для поиска тестов по имени категории, его использать тут надо. не будут админы задавать параметр категории как цифры. зачем админам знать id категорий? просто пишут/выбирают из опций названия

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> + def passed_all_tests_of_the_parametr_level(badge, testpassage)
уровень сюда тоже параметром передавай, чтобы по параметру баджа выбирать что проверять

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +   TestPassage.where(user_id: testpassage.user_id, test_success: true).each do |x|
надо свести руби код к минимуму. у тебя тут по факту два запроса. один запрос - получить все тесты уровня, второй запрос - получить все тесты уровня, которые прошел пользователь. и дальше сравнить два массива

2021-12-22 18:57 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <% Badge.check_badge %>
ого, это что такое? что за вызов логики во вьюхе? это надо убрать отсюда

2021-12-22 18:57 UTC, BubuntuClu commented on config/routes.rb
> +   resources :badges, only: %i[index]
в чем разница между этим роутом и тем что выше?
сделай один роут, где пользователь видит то что получил и что доступно

2021-12-22 18:57 UTC, BubuntuClu commented on db/migrate/20211221112957_add_parametr_to_badges.rb
> +    add_column :badges, :parametr, :string, default: ''
почему отдельная миграция? откати создание таблицы баджей и там добавь поле.

2021-12-22 18:57 UTC, BubuntuClu commented on db/migrate/20211221112957_add_parametr_to_badges.rb
> +    add_column :badges, :parametr, :string, default: ''
можно назвать поле как `value`, `parametr` как-то странно выглядит

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def before_update_test_success
вызывай этот метод не через колбэк, а напрямую из контроллера, когда тест успешно пройден

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +   testpassage = TestPassage.last
почему тут последний берется? это неправильно. надо брать каждый пройденный и для него проверять. текущая логика не гарантирует что будет обрабатываться то прохождение, что ты сделал. вполне может вклиниться прохождение другим пользователем

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +     badge.metods_check(badge, testpassage)
`user.badges << badge if send("#{badge.rule.name}", badge.value)`

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +   rule_name = str_for_send(Rule.find(badge.rule_id).name)
используй ассоциации, не надо каждый раз самому писать поиск объектов

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +   badges = Badge.where(rule_id: rule_id)
у тебя основной цикл идет через перебор баджа, зачем тебе о5 делать запрос за баджами? выдавай тот, который сейчас прошел проверку

2021-12-22 18:57 UTC, BubuntuClu commented on app/models/badge.rb
> +     badge.metods_check(badge, testpassage)
таким образом у тебя уйдет дублирование кода `add_badge(badge.rule_id, testpassage.user_id)`
только надо будет переделать методы на то чтобы они возвращали `true/false`

2021-12-24 18:14 UTC, BubuntuClu requested changes

2021-12-24 18:14 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      @test_passage.before_update_test_success
before_update_test_success - метод надо назвать как-то подругому

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/badge.rb
> +  #before_action :authenticate_user!
это что тут забыло? надо убрать, а не закомментировать

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/badge.rb
> +  has_many :users, through: :user_badges
```
  has_many :users, through: :user_badges
  has_many :users
```
у тебя две ассоциации с одним именем, одна из них не будет работать

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/badge.rb
> +
много пустых строк

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/badge.rb
> +  validates :name, presence: true
как-то странно выглядит поле `name` в отношении бейджа. `title` может лучше?

2021-12-24 18:14 UTC, BubuntuClu commented on db/migrate/20211221112957_add_parametr_to_badges.rb
> +    add_column :badges, :parametr, :string, default: ''
это не поправлено, эта миграция зачем-то все еще существует

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :badges
аналогично и тут, две ассоциации с одним именем

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/test_passage.rb
> +
лишние пустые строки

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_update :before_update_next_question#, :before_update_test_success
не комментировать, а удалять надо ненужный код

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def before_update_test_success
метод стоит переименовать

2021-12-24 18:14 UTC, BubuntuClu commented on app/models/my_badge.rb
> +class MyBadge < ApplicationRecord
для этой модели нет таблицы в БД. да и зачем вообще эта модель?

2021-12-24 18:14 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @rules = Rule.all
задал вопрос в слак

2021-12-24 18:14 UTC, BubuntuClu commented on app/controllers/my_badges_controller.rb
> +  skip_before_action :authenticate_user!, raise: false
задал вопрос в слак

2021-12-24 18:14 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <% BadgeService.new(current_user) %>
1 - уже писал тебе, что не должно быть подобных вызовов во вьюхе. вызывай это в контроллере
2 - судя по тому как ты написал, ты просто инициализировал объект. а где вызов логики какой-то?

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def initialize(current_user)
нельзя помещать выполнение логики в инициализацию. нужно делать для этого отдельный метод. у сервисов это метод `call`

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def initialize(current_user)
проверку надо делать не для пользователя, а для только что пройденного теста

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    testpassage = TestPassage.where(user_id: current_user.id).last
если пассаж сюда передашь, не надо будет делать вот это

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def str_for_send(str)
странный метод. что мешает тебе задать имя правила в нужном формате?

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +
мног опустых строк

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    if Category.where(title: badge.parametr)
`Category.where(title: badge.parametr)` - запрос дублируется

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      tests_backend = Test.where(category_id: Category.where(title: badge.parametr)[0].id).pluck(:id)
1 - `Category.where(title: badge.parametr)[0].id` - чтобы не делать такой костыль можно использовать `find`
2 - у тебя есть метод поиска тестов по имени категории, используй тут этот метод. зря что ли его писал?)

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      tests_user = TestPassage.where(user_id: testpassage.user_id, test_success: true).pluck(:test_id).uniq
такой запрос вернет все успешно пройденные тесты, не только по заданной категории. массивы практически никогда не будут равны. надо добавить фильтрацию по категории

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      tests_backend = Test.where(category_id: Category.where(title: badge.parametr)[0].id).pluck(:id)
`tests_backend` - а если тест не `backend` категории?

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +   tests_user = TestPassage.where(user_id: testpassage.user_id, test_id: testpassage.test_id, test_success: true).pluck(:test_id)
`test_success: true` - не так надо проверять что тест успешен. в данном случае у тебя может быть 100500 провальных попыток и только потом одна успешная, ты выдашь бейдж.
нужно по-другому проверить что тест успешен

2021-12-24 18:14 UTC, BubuntuClu commented on app/services/badge_service.rb
> +   TestPassage.where(user_id: testpassage.user_id, test_success: true).each do |x|
этот перебор надо убрать и использовать два запроса к БД и сравнить результаты

2021-12-24 18:14 UTC, BubuntuClu commented on app/views/admin/badges/_badge.html.erb
> +  <td class="id"><%= @rules.find(badge.rule_id).name %></td>
ассоциации используй. не должно быть явных запросов во вьюхах

2021-12-24 18:14 UTC, BubuntuClu commented on app/views/badges/_badge.html.erb
> +  <td class="id"><%= @rules.find(badge.rule_id).name %></td>
и тут

2021-12-26 17:47 UTC, BubuntuClu requested changes

2021-12-26 17:47 UTC, BubuntuClu commented on app/services/badge_service.rb
> +   tests_user = TestPassage.where(user_id: testpassage.user_id, test_id: testpassage.test_id).pluck(:test_id, :test_success)
`TestPassage.where(user_id: testpassage.user_id, test_id: testpassage.test_id).count ==1 && testpassage.success?`

на счет `success?` не уверен, как там у тебя метод называется, который определяет что тест пройден успешно?

2021-12-26 17:47 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    level_current_test = Test.find(testpassage.test_id).level
а почему так ищется уровень? он же у тебя хранится в параметра баджа как значение для поиска

2021-12-26 17:47 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      tests_user = Test.where(category_id: Category.where(title: badge.parametr)[0].id).joins("JOIN test_passages ON test_passages.user_id = #{testpassage.user_id} AND test_passages.test_success = tr
1 - `Category.where(title: badge.parametr)[0].id` - чтобы не писать так, есть метод `find`, который ты использовал много раз
2 - используй метод из модели теста, не надо дублировать код, там у тебя запрос написан лучше чем тут, там через `join`

2021-12-26 17:47 UTC, BubuntuClu commented on db/migrate/20211221112957_add_parametr_to_badges.rb
> +    add_column :badges, :parametr, :string, default: ''
и вот этот коммент все еще ждет исправления

2021-12-28 07:08 UTC, merged